import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { GAMES } from '@rallypoint-cmd/shared'
import { invalidateAdminCredsCache, readAdminCreds } from './admin-creds.js'

// The panel writes these credentials through the settings adapters and
// reads them back here. The two sides are only correct together, so the
// fixtures below are written in each game's real config syntax.

const tmpDirs: string[] = []

function installWith(rel: string, content: string): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'admin-creds-'))
  tmpDirs.push(dir)
  const file = path.join(dir, rel)
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, content)
  return dir
}

afterEach(() => {
  invalidateAdminCredsCache()
  while (tmpDirs.length > 0) fs.rmSync(tmpDirs.pop()!, { recursive: true, force: true })
})

describe('readAdminCreds', () => {
  it('reads ARK’s RCON port and admin password out of GameUserSettings.ini', () => {
    const dir = installWith(
      'ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini',
      ['[ServerSettings]', 'RCONEnabled=True', 'RCONPort=27020', 'ServerAdminPassword=ark-secret', ''].join('\n'),
    )
    expect(readAdminCreds('ark-survival-evolved', dir)).toEqual({ port: 27020, password: 'ark-secret' })
  })

  it('reads 7 Days to Die’s telnet settings out of serverconfig.xml', () => {
    const dir = installWith(
      'serverconfig.xml',
      [
        '<?xml version="1.0"?>',
        '<ServerSettings>',
        '  <property name="TelnetEnabled" value="true"/>',
        '  <property name="TelnetPort" value="8081"/>',
        '  <property name="TelnetPassword" value="telnet-secret"/>',
        '</ServerSettings>',
      ].join('\n'),
    )
    expect(readAdminCreds('7-days-to-die', dir)).toEqual({ port: 8081, password: 'telnet-secret' })
  })

  it('reads Project Zomboid’s RCON settings out of its server ini', () => {
    const dir = installWith('Zomboid/Server/rallypoint.ini', 'RCONPort=27025\nRCONPassword=pz-secret\n')
    expect(readAdminCreds('project-zomboid', dir)).toEqual({ port: 27025, password: 'pz-secret' })
  })

  it('reads a Source server.cfg rcon_password and takes the port from the registry', () => {
    const dir = installWith('tf/cfg/server.cfg', 'hostname "Rallypoint"\nrcon_password "tf-secret"\nsv_pure 1\n')
    // Source games declare no port in the cfg — it is whatever the
    // registry entry says, so assert the wiring rather than a constant.
    const declared = GAMES['team-fortress-2']!.ports.find((p) => p.name === 'rcon')?.port ?? null
    expect(readAdminCreds('team-fortress-2', dir)).toEqual({ port: declared, password: 'tf-secret' })
  })

  it('reads Rust’s RCON convars out of the panel-owned launch conf', () => {
    const dir = installWith(
      'rallypoint-launch.conf',
      ['# Generated by rallypoint-cmd', '+rcon.port 28016', '+rcon.password rust-secret', '+rcon.web 1', ''].join('\n'),
    )
    expect(readAdminCreds('rust', dir)).toEqual({ port: 28016, password: 'rust-secret' })
  })

  it('reports no password when the game has not written its config yet', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'admin-creds-empty-'))
    tmpDirs.push(dir)
    expect(readAdminCreds('ark-survival-evolved', dir).password).toBeNull()
  })

  it('has nothing to say about games with no admin channel', () => {
    expect(readAdminCreds('valheim', '/nonexistent')).toEqual({ port: null, password: null })
  })

  it('picks up a rewritten password once the cache is invalidated', () => {
    const dir = installWith('Zomboid/Server/rallypoint.ini', 'RCONPort=27025\nRCONPassword=first\n')
    expect(readAdminCreds('project-zomboid', dir).password).toBe('first')
    fs.writeFileSync(path.join(dir, 'Zomboid/Server/rallypoint.ini'), 'RCONPort=27025\nRCONPassword=second\n')
    invalidateAdminCredsCache(dir)
    expect(readAdminCreds('project-zomboid', dir).password).toBe('second')
  })
})
