import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import fs from 'node:fs'
import path from 'node:path'
import {
  cpuQuotaPctSchema,
  effectiveResources,
  gameBySlug,
  memoryLimitSchema,
  templateUnitFor,
  type GameDef,
  type ResourceOverrides,
} from '@rallypoint-cmd/shared'
import type { Env } from '../env.js'
import type { Logger } from '../logger.js'
import { SYSTEMCTL_BIN, assertAllowedSlug } from './constants.js'

const execFileAsync = promisify(execFile)

// Provisions/deprovisions the systemd side of a game unit: the start
// script the template unit execs, and the per-instance drop-in carrying
// WorkingDirectory / stop signal / memory limits.
//
// Both files are rendered from the game registry
// (packages/shared/src/games.ts) — it is the single source of truth for
// start command, stop signal and memory caps, so there is no second
// table to keep in lockstep.

export const GAMES_CONF_ROOT = '/etc/rallypoint-cmd/games'
export const SYSTEMD_UNIT_DIR = '/etc/systemd/system'

export interface UnitProvisioner {
  provision(slug: string, overrides?: Partial<ResourceOverrides> | null): Promise<void>
  deprovision(slug: string): Promise<void>
}

// `{{INSTALL_DIR}}` in a registry argument expands to the server's own
// install dir. Needed because HOME is not a universal redirect: Project
// Zomboid runs on the JVM, which derives `user.home` from the passwd
// entry rather than $HOME, so it has to be told its data dir outright.
function startCommandLine(game: GameDef, installDir: string): string {
  const args = game.startCommand.args.map((arg) => arg.replaceAll('{{INSTALL_DIR}}', installDir))
  return [game.startCommand.bin, ...args].join(' ')
}

// The script the template unit execs. Windows-only servers resolve the
// Wine loader at run time rather than install time: Debian ships the
// 64-bit loader as `wine64` on some releases and as a single multi-arch
// `wine` on others, and Wine >= 9 dropped the wine64 name entirely.
// Baking an absolute path turns a missing binary into an opaque
// "exec: not found" from the unit.
export function renderStartScript(game: GameDef, installDir: string): string {
  const cmd = startCommandLine(game, installDir)
  if (game.platform === 'windows') {
    return `#!/bin/sh
# Generated by rallypoint-cmd — do not edit (regenerate instead).
cd "${installDir}"
export HOME="${installDir}"
export WINEPREFIX="${installDir}/.wine"
export WINEDEBUG=-all
WINE_BIN="\${WINE_BIN:-}"
if [ -z "$WINE_BIN" ]; then
  for c in wine64 wine; do
    if command -v "$c" >/dev/null 2>&1; then WINE_BIN="$(command -v "$c")"; break; fi
  done
fi
if [ -z "$WINE_BIN" ]; then
  echo "${game.slug}: no Wine loader found (looked for wine64, wine on PATH)." >&2
  echo "Install it in the container:  apt-get install -y wine wine64 || apt-get install -y wine" >&2
  exit 127
fi
exec "$WINE_BIN" ${cmd}
`
  }
  // Games with a panel-owned launch conf get their extra args from it.
  // The conf sets the positional parameters (`set -- 'a' 'b'`) and they
  // are forwarded as "$@", so a value containing spaces — a server name,
  // typically — stays one argument. The file is dot-sourced, so only the
  // launch-conf settings adapter writes it, and it restricts values to a
  // strict charset. `set --` first clears the parameters, so a missing
  // conf simply contributes nothing.
  const launchConf = game.launchConfFile
    ? `set --
[ -f "./${game.launchConfFile}" ] && . "./${game.launchConfFile}"
`
    : ''
  return `#!/bin/sh
# Generated by rallypoint-cmd — do not edit (regenerate instead).
cd "${installDir}"
export HOME="${installDir}"
export LD_LIBRARY_PATH="${installDir}:${installDir}/linux64:\${LD_LIBRARY_PATH:-}"
${launchConf}exec ${cmd}${game.launchConfFile ? ' "$@"' : ''}
`
}

export function renderInstanceDropIn(
  game: GameDef,
  installDir: string,
  overrides?: Partial<ResourceOverrides> | null,
): string {
  const effective = effectiveResources(game, overrides)
  // Defense in depth: these values are written verbatim into a file
  // systemd trusts, so re-validate here even though the route already
  // parsed them — a value with a newline in it must never reach /etc.
  for (const value of [effective.memoryHigh, effective.memoryMax]) {
    if (value !== null && !memoryLimitSchema.safeParse(value).success) {
      throw new Error(`invalid memory limit ${JSON.stringify(value)}`)
    }
  }
  if (effective.cpuQuotaPct !== null && !cpuQuotaPctSchema.safeParse(effective.cpuQuotaPct).success) {
    throw new Error(`invalid CPU quota ${JSON.stringify(effective.cpuQuotaPct)}`)
  }
  const lines = [
    '# Generated by rallypoint-cmd — do not edit (regenerate instead).',
    '[Service]',
    `WorkingDirectory=${installDir}`,
    `KillSignal=${game.stopSignal}`,
    `TimeoutStopSec=${game.timeoutStopSec}`,
  ]
  if (effective.memoryHigh) lines.push(`MemoryHigh=${effective.memoryHigh}`)
  if (effective.memoryMax) lines.push(`MemoryMax=${effective.memoryMax}`)
  if (effective.cpuQuotaPct !== null) lines.push(`CPUQuota=${effective.cpuQuotaPct}%`)
  // ProtectSystem=strict in the template unit makes the whole filesystem
  // read-only; the game needs its own install dir writable (saves, logs,
  // and for Windows servers the Wine prefix under it).
  lines.push(`ReadWritePaths=${installDir}`)
  return `${lines.join('\n')}\n`
}

export function createRealUnitProvisioner(env: Env, logger: Logger): UnitProvisioner {
  async function systemctl(args: string[]): Promise<void> {
    await execFileAsync(SYSTEMCTL_BIN, args, { timeout: 60_000 })
  }

  return {
    async provision(slug, overrides) {
      assertAllowedSlug(slug)
      const game = gameBySlug(slug)
      if (!game) throw new Error(`unknown game slug ${slug}`)
      const installDir = path.join(env.GAMES_ROOT, slug)
      const confDir = path.join(GAMES_CONF_ROOT, slug)
      const dropInDir = path.join(SYSTEMD_UNIT_DIR, `${templateUnitFor(slug)}.d`)

      fs.mkdirSync(installDir, { recursive: true })
      fs.mkdirSync(confDir, { recursive: true })
      fs.mkdirSync(dropInDir, { recursive: true })

      fs.writeFileSync(path.join(confDir, 'start.sh'), renderStartScript(game, installDir), {
        mode: 0o755,
      })
      // writeFileSync only applies `mode` when it creates the file, so a
      // regenerated script would keep whatever mode it had.
      fs.chmodSync(path.join(confDir, 'start.sh'), 0o755)
      fs.writeFileSync(path.join(dropInDir, 'instance.conf'), renderInstanceDropIn(game, installDir, overrides), {
        mode: 0o644,
      })
      fs.chmodSync(path.join(dropInDir, 'instance.conf'), 0o644)

      // Modifying an existing template unit's drop-ins — systemd needs to
      // re-read them before the next start.
      await systemctl(['daemon-reload'])
      await systemctl(['enable', '-q', templateUnitFor(slug)])
      logger.info('unit provisioned', { slug, unit: templateUnitFor(slug), installDir })
    },

    async deprovision(slug) {
      assertAllowedSlug(slug)
      // Best-effort: a unit that was never enabled (or already gone) must
      // not block deleting the server row.
      try {
        await systemctl(['disable', '-q', '--now', templateUnitFor(slug)])
      } catch (err) {
        logger.warn('unit disable failed (continuing)', {
          slug,
          err: err instanceof Error ? err.message : String(err),
        })
      }
      fs.rmSync(path.join(SYSTEMD_UNIT_DIR, `${templateUnitFor(slug)}.d`), {
        recursive: true,
        force: true,
      })
      fs.rmSync(path.join(GAMES_CONF_ROOT, slug), { recursive: true, force: true })
      await systemctl(['daemon-reload'])
      // Game files under GAMES_ROOT/<slug> are left alone — deleting a
      // server row is not deleting a world.
      logger.info('unit deprovisioned', { slug, unit: templateUnitFor(slug) })
    },
  }
}

export function createFakeUnitProvisioner(logger: Logger): UnitProvisioner {
  async function run(verb: 'add' | 'remove', slug: string, overrides?: Partial<ResourceOverrides> | null): Promise<void> {
    assertAllowedSlug(slug)
    logger.info('fake unit provisioner', { verb, slug, ...(overrides ? { overrides } : {}) })
  }
  return {
    provision: (slug, overrides) => run('add', slug, overrides),
    deprovision: (slug) => run('remove', slug),
  }
}
