import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import fs from 'node:fs'
import path from 'node:path'
import { gameBySlug, templateUnitFor, type GameDef } from '@rallypoint-cmd/shared'
import type { Env } from '../env.js'
import type { Logger } from '../logger.js'
import { SYSTEMCTL_BIN, assertAllowedSlug } from './constants.js'

const execFileAsync = promisify(execFile)

// Provisions/deprovisions the systemd side of a game unit: the start
// script the template unit execs, and the per-instance drop-in carrying
// WorkingDirectory / stop signal / memory limits.
//
// Both files are rendered from the game registry
// (packages/shared/src/games.ts) — it is the single source of truth for
// start command, stop signal and memory caps, so there is no second
// table to keep in lockstep.

export const GAMES_CONF_ROOT = '/etc/rallypoint-cmd/games'
export const SYSTEMD_UNIT_DIR = '/etc/systemd/system'

export interface UnitProvisioner {
  provision(slug: string): Promise<void>
  deprovision(slug: string): Promise<void>
}

function startCommandLine(game: GameDef): string {
  return [game.startCommand.bin, ...game.startCommand.args].join(' ')
}

// The script the template unit execs. Windows-only servers resolve the
// Wine loader at run time rather than install time: Debian ships the
// 64-bit loader as `wine64` on some releases and as a single multi-arch
// `wine` on others, and Wine >= 9 dropped the wine64 name entirely.
// Baking an absolute path turns a missing binary into an opaque
// "exec: not found" from the unit.
export function renderStartScript(game: GameDef, installDir: string): string {
  const cmd = startCommandLine(game)
  if (game.platform === 'windows') {
    return `#!/bin/sh
# Generated by rallypoint-cmd — do not edit (regenerate instead).
cd "${installDir}"
export HOME="${installDir}"
export WINEPREFIX="${installDir}/.wine"
export WINEDEBUG=-all
WINE_BIN="\${WINE_BIN:-}"
if [ -z "$WINE_BIN" ]; then
  for c in wine64 wine; do
    if command -v "$c" >/dev/null 2>&1; then WINE_BIN="$(command -v "$c")"; break; fi
  done
fi
if [ -z "$WINE_BIN" ]; then
  echo "${game.slug}: no Wine loader found (looked for wine64, wine on PATH)." >&2
  echo "Install it in the container:  apt-get install -y wine wine64 || apt-get install -y wine" >&2
  exit 127
fi
exec "$WINE_BIN" ${cmd}
`
  }
  return `#!/bin/sh
# Generated by rallypoint-cmd — do not edit (regenerate instead).
cd "${installDir}"
export HOME="${installDir}"
export LD_LIBRARY_PATH="${installDir}:${installDir}/linux64:\${LD_LIBRARY_PATH:-}"
exec ${cmd}
`
}

export function renderInstanceDropIn(game: GameDef, installDir: string): string {
  const lines = [
    '# Generated by rallypoint-cmd — do not edit (regenerate instead).',
    '[Service]',
    `WorkingDirectory=${installDir}`,
    `KillSignal=${game.stopSignal}`,
    `TimeoutStopSec=${game.timeoutStopSec}`,
  ]
  if (game.memoryHigh) lines.push(`MemoryHigh=${game.memoryHigh}`)
  if (game.memoryMax) lines.push(`MemoryMax=${game.memoryMax}`)
  // ProtectSystem=strict in the template unit makes the whole filesystem
  // read-only; the game needs its own install dir writable (saves, logs,
  // and for Windows servers the Wine prefix under it).
  lines.push(`ReadWritePaths=${installDir}`)
  return `${lines.join('\n')}\n`
}

export function createRealUnitProvisioner(env: Env, logger: Logger): UnitProvisioner {
  async function systemctl(args: string[]): Promise<void> {
    await execFileAsync(SYSTEMCTL_BIN, args, { timeout: 60_000 })
  }

  return {
    async provision(slug) {
      assertAllowedSlug(slug)
      const game = gameBySlug(slug)
      if (!game) throw new Error(`unknown game slug ${slug}`)
      const installDir = path.join(env.GAMES_ROOT, slug)
      const confDir = path.join(GAMES_CONF_ROOT, slug)
      const dropInDir = path.join(SYSTEMD_UNIT_DIR, `${templateUnitFor(slug)}.d`)

      fs.mkdirSync(installDir, { recursive: true })
      fs.mkdirSync(confDir, { recursive: true })
      fs.mkdirSync(dropInDir, { recursive: true })

      fs.writeFileSync(path.join(confDir, 'start.sh'), renderStartScript(game, installDir), {
        mode: 0o755,
      })
      // writeFileSync only applies `mode` when it creates the file, so a
      // regenerated script would keep whatever mode it had.
      fs.chmodSync(path.join(confDir, 'start.sh'), 0o755)
      fs.writeFileSync(path.join(dropInDir, 'instance.conf'), renderInstanceDropIn(game, installDir), {
        mode: 0o644,
      })
      fs.chmodSync(path.join(dropInDir, 'instance.conf'), 0o644)

      // Modifying an existing template unit's drop-ins — systemd needs to
      // re-read them before the next start.
      await systemctl(['daemon-reload'])
      await systemctl(['enable', '-q', templateUnitFor(slug)])
      logger.info('unit provisioned', { slug, unit: templateUnitFor(slug), installDir })
    },

    async deprovision(slug) {
      assertAllowedSlug(slug)
      // Best-effort: a unit that was never enabled (or already gone) must
      // not block deleting the server row.
      try {
        await systemctl(['disable', '-q', '--now', templateUnitFor(slug)])
      } catch (err) {
        logger.warn('unit disable failed (continuing)', {
          slug,
          err: err instanceof Error ? err.message : String(err),
        })
      }
      fs.rmSync(path.join(SYSTEMD_UNIT_DIR, `${templateUnitFor(slug)}.d`), {
        recursive: true,
        force: true,
      })
      fs.rmSync(path.join(GAMES_CONF_ROOT, slug), { recursive: true, force: true })
      await systemctl(['daemon-reload'])
      // Game files under GAMES_ROOT/<slug> are left alone — deleting a
      // server row is not deleting a world.
      logger.info('unit deprovisioned', { slug, unit: templateUnitFor(slug) })
    },
  }
}

export function createFakeUnitProvisioner(logger: Logger): UnitProvisioner {
  async function run(verb: 'add' | 'remove', slug: string): Promise<void> {
    assertAllowedSlug(slug)
    logger.info('fake unit provisioner', { verb, slug })
  }
  return {
    provision: (slug) => run('add', slug),
    deprovision: (slug) => run('remove', slug),
  }
}
